### ISSUE TITLE
DB設計

### ISSUE THREAD

**Issue by yosimurat** [mashupwork/ruffnote-mailform#11]

**Comment by yosimurat** [comment]
メールデータの物理設計 参考：#10

**Comment by yosimurat** [comment]
https://docs.google.com/spreadsheets/d/1KjrRDXs0EJ7BbcO6XFpFzZtbJni6rMjrja1tQYjZrWg/edit?usp=sharing

**Comment by yosimurat** [comment]
昨日の振り返り
* メールデータからページ情報は分離した
* メール本文もＤＢに持つようにした
* 宛先マスタを持つようにした
* カテゴリマスタを用意
　→ これは第一フェーズでは不要かも

**Comment by pandeiro245** [comment]
@yosimurat ミニマムでお願いします！「DB」っていうのはMySQLのことですか？今回の最低要件はメールが送られてRuffnoteにデータ保存できればOKです。

**Comment by yosimurat** [comment]
@pandeiro245 
了解です、できるだけミニマムにします。

**Comment by yosimurat** [comment]
@pandeiro245  MySQLにメール本文を持たせる予定です。

**Comment by yosimurat** [comment]
書きかけの状態で下書きを保存したりできるようにすることとかを考えるとRuffnoteのみに本文を持たせておいた方がいいかと思います。

**Comment by yosimurat** [comment]
カテゴリマスタはページ情報持ってればいらなそう

**Comment by yosimurat** [comment]
下記のテーブル構成で一旦FIX
ユーザマスタ
メールデータ
ページ情報
宛先マスタ
汎用マスタ
