### ISSUE TITLE
invalid_grantエラー （oauth）

### ISSUE THREAD

**Issue by yosimurat** [mashupwork/ruffnote-mailform#17]
#6 で出たエラーの対応
https://github.com/ruffnote/chatwork2ruff/issues/15 と同じエラー

![image](https://cloud.githubusercontent.com/assets/1275365/16264970/c0829f4a-38b7-11e6-84cd-c1e5f5ea7933.png)

invalid_grant: The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client. {"error":"invalid_grant","error_description":"The provided authorization grant is invalid, expired, revoked, does not match the redirection URI used in the authorization request, or was issued to another client."}

**Comment by yosimurat** [comment]
接続先のruffnoteをhttp://ruffnote.com(本番)に変えても同じエラーとなる

**Comment by yosimurat** [comment]
これはハマる。手がかり無いかんじ。

原因を推測してみる

１）ただの設定のケアレスミスで、client_secretが合っていない。
２）ドメインがＩＰアドレスなのがＮＧ
３）ruffnote側でエラーが発生している
４）認証自体はうまくいっているが、後続の処理でコケている
５）サーバーの日付があっていない（ロケールが不一致とか）
６）gemが足りない
７）なんらかのgemが競合している
８）

**Comment by yosimurat** [comment]
試してみること

Ａ） ケアレスミスと考え、あえて間違ったクライアントＩＤを入れてみたりしてエラーが変わるか確認する
Ｂ）環境を疑い、Windows機ではなくＭａｃ機で試してみる

**Comment by pandeiro245** [comment]
@yosimurat ここに登録しているコールバックURLってなんですか？？
https://ruffnote.com/oauth/applications

**Comment by yosimurat** [comment]
@pandeiro245 
http://192.168.99.100:3001/auth/ruffnote/callback
です。

**Comment by yosimurat** [comment]
![image](https://cloud.githubusercontent.com/assets/1275365/16275501/3784d63a-38e5-11e6-8da1-938fc8277e1b.png)

**Comment by yosimurat** [comment]
rubyのバージョン指定がなかった。これも原因候補

**Comment by yosimurat** [comment]
Macでも同じだった
環境関係ないとしたら、やはりケアレスミス？
あとrubyのバージョン指定入れとこう
![image](https://cloud.githubusercontent.com/assets/1275365/16276229/786f673e-38e8-11e6-9555-c548778ac770.png)

**Comment by yosimurat** [comment]
ruffnote/chatwork2ruff#15 と同じエラー
上記に振り返って考え直してみる。

**Comment by yosimurat** [comment]
client_idをわざと間違えた場合のエラー
![image](https://cloud.githubusercontent.com/assets/1275365/16276966/c0284f0c-38eb-11e6-9fcb-e5780871beff.png)

**Comment by yosimurat** [comment]
Client Secretをわざと間違えた場合
ちょっと、本issueのエラーと詳細が異なる
![image](https://cloud.githubusercontent.com/assets/1275365/16277038/1742dfd2-38ec-11e6-9415-555300ea689e.png)

**Comment by yosimurat** [comment]
Callback URLが間違っている場合
![image](https://cloud.githubusercontent.com/assets/1275365/16277260/2f20e51c-38ed-11e6-98a1-9410b0462f1f.png)

**Comment by yosimurat** [comment]
rubyバージョン何にしよう。chatwork2ruffに合わせて2.2.5系か最新の2.3.1系

現状：Windows機 2.2.5 ／ Mac機 2.3.0
しかし、以前はchatwork2ruffはログインでいていたんだが、違いが思い浮かばない

**Comment by yosimurat** [comment]
一度、chatwork2ruffに戻ってやりなおすか

もともと認証は出来ていたはず。前回は特に手間取ってもいない。
https://github.com/ruffnote/chatwork2ruff/issues/1

**Comment by yosimurat** [comment]
https://ruffnote.slack.com/archives/random/p1466696759000032

```
gem 'omniauth-oauth2', '1.3.1'

$ bundle update omniauth-oauth2
```
情報ありがとうございます！

**Comment by yosimurat** [comment]
![image](https://cloud.githubusercontent.com/assets/1275365/16315135/fe1f5d16-39bb-11e6-86eb-b80ce5ed587d.png)
