### ISSUE TITLE
ShiwakeプロジェクトのコピーからReactのスケルトンを構築

### ISSUE THREAD

**Issue by yosimurat** [mashupwork/ruffnote-mailform#8]

**Comment by pandeiro245** [comment]
@yosimurat こちらの件、slackで連絡しました！

**Comment by yosimurat** [comment]
ベースとなるプロジェクトの選定

選定条件
１） reactを使っていること
２） ruffnoteとoauth連携ができる → これはhttps://github.com/ruffnote/chatwork2ruffを参考にすればいい
３） dbはmysqlを使っている → これも３）を参考にすればいい
４）メール送信処理のユーティリティ → これはletter_opener_webを使う

希望要件
a） reactはいくつか技術、組み合わせがあるので、shiwakeよりいい組み合わせの案件があれば、そちらをベースとしたい。
b) ruffote ＡＰＩを用いたノートやページの作成など実装例として参考になるもの

候補１：shiwake案件  https://github.com/pandeiro245/shiwake
候補２：？ 一度、slackで他の人の意見を聞く

**Comment by yosimurat** [comment]
React見送りににつき、
今回はchatwork2ruffをベースにする
