### ISSUE TITLE
メールフォームにおいてReactを使用するポイントを検討する

### ISSUE THREAD

**Issue by yosimurat** [mashupwork/ruffnote-mailform#9]
画面の候補は以下の通り
reactの使いどころを検討する

 ログイン画面を作成する（Ruffnoteログイン）　
 メール作成画面
 作成中メール一覧
 メール送信履歴一覧
 メールの参照

**Comment by pandeiro245** [comment]
@yosimurat 無理にReact使わなくても大丈夫ですよｗ

**Comment by yosimurat** [comment]
@pandeiro245 了解です

**Comment by yosimurat** [comment]
React検討箇所

ログイン画面を作成する（Ruffnoteログイン）　
　→ いらない

メール作成画面
　→ 1) メール書きかけで下書きを保存する時はAjaxで処理すべき
　→ 2) メール書きかけのまま離席した場合の一時保存など

一次フェーズではミニマムで１）まではやる、あるいは最後までReact使わないか

**Comment by yosimurat** [comment]
今回は見送り
